### PR TITLE
Add support for Discord Usernames

### PR DESCRIPTION
**Pull request by Salty-Coder**
Will no longer show discriminator as #0 if the user has a username.

### CODE REVIEW

**Comment by iyu46** [comment]
Thank you! I haven't been able to work on the plugin recently because of one of my drives dying on my desktop. I'd like to merge this change in (I'd totally forgotten about it becoming an issue) but I'd need to do some paperwork changes first (like bumping the version, adding a changelog entry, etc). I am also now briefly considering adding a check to remove the display of "#0" in any entries that have already been saved to the history logs by modifying the spot where cached info is displayed on the UI modal.

Again though thank you so much!! I'll return to this when I have the time to make those additional changes. If you'd like to make them yourself and add them to this PR feel free as well!

**Comment by Salty-Coder** [comment]
Not sure if the [most recent commit](https://github.com/iyu46/RemovedConnectionAlerts/pull/10/commits/34c4120de9a41814f2a2c9291eb9b8f2972c4bcf) is exactly what your after but I assume that's somewhat correct.

**Comment by iyu46** [comment]
finally got my computer running again! ran my linter for some changes on your commit, and added fetching the current nickname of the person that removed you next to their handle (since the nicknames are usually more easily identifiable than the usernames)

I want to give you a chance to check my work too, so let me know if anything looks weird as well! I'll merge in three days or so if nothing pops up :D thank you again!

**Comment by Salty-Coder** [comment]
> finally got my computer running again! ran my linter for some changes on your commit, and added fetching the current nickname of the person that removed you next to their handle (since the nicknames are usually more easily identifiable than the usernames)
> 
> 
> 
> I want to give you a chance to check my work too, so let me know if anything looks weird as well! I'll merge in three days or so if nothing pops up :D thank you again!

Hi again. I looked through your commit. It all seems to look good. I can’t spot any clear issues with  it so I’d say it’s ready to go. Thanks again for using my usernames commit :)

**Pull request merged**
